<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260628215400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add operator inspection metadata for runs and approvals.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE agent_run ADD source_event_id VARCHAR(160) DEFAULT NULL');
        $this->addSql('ALTER TABLE agent_run ADD requester_id VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE agent_run ADD repository_clones JSON NOT NULL DEFAULT \'[]\'');
        $this->addSql('CREATE TABLE run_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, run_id INT NOT NULL, type VARCHAR(64) NOT NULL, message TEXT NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_run_event_run_id ON run_event (run_id)');
        $this->addSql('ALTER TABLE run_event ADD CONSTRAINT FK_run_event_run_id FOREIGN KEY (run_id) REFERENCES agent_run (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE approval_request ADD run_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_approval_request_run_id ON approval_request (run_id)');
        $this->addSql('ALTER TABLE approval_request ADD CONSTRAINT FK_approval_request_run_id FOREIGN KEY (run_id) REFERENCES agent_run (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE approval_request DROP CONSTRAINT FK_approval_request_run_id');
        $this->addSql('ALTER TABLE run_event DROP CONSTRAINT FK_run_event_run_id');
        $this->addSql('DROP TABLE run_event');
        $this->addSql('DROP INDEX IDX_approval_request_run_id');
        $this->addSql('ALTER TABLE approval_request DROP run_id');
        $this->addSql('ALTER TABLE agent_run DROP source_event_id');
        $this->addSql('ALTER TABLE agent_run DROP requester_id');
        $this->addSql('ALTER TABLE agent_run DROP repository_clones');
    }
}
