<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260628214900 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create explicit global memories.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE global_memory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(120) NOT NULL, source_platform VARCHAR(32) NOT NULL, source_thread_id VARCHAR(160) NOT NULL, source_message_id VARCHAR(160) NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE global_memory');
    }
}
