<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove the obsolete approval and global memory systems.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE approval_request');
        $this->addSql('DROP TABLE global_memory');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE approval_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, run_id INT DEFAULT NULL, action VARCHAR(120) NOT NULL, target_system VARCHAR(80) NOT NULL, workflow_name VARCHAR(120) NOT NULL, requester_id VARCHAR(120) NOT NULL, expected_effect TEXT NOT NULL, sensitivity VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) NOT NULL, approver_id VARCHAR(120) DEFAULT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_approval_request_run_id ON approval_request (run_id)');
        $this->addSql('ALTER TABLE approval_request ADD CONSTRAINT FK_approval_request_run_id FOREIGN KEY (run_id) REFERENCES agent_run (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE global_memory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(120) NOT NULL, source_platform VARCHAR(32) NOT NULL, source_thread_id VARCHAR(160) NOT NULL, source_message_id VARCHAR(160) NOT NULL, PRIMARY KEY(id))');
    }
}
