<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260628214200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create approval requests.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE approval_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(120) NOT NULL, target_system VARCHAR(80) NOT NULL, workflow_name VARCHAR(120) NOT NULL, requester_id VARCHAR(120) NOT NULL, expected_effect TEXT NOT NULL, sensitivity VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) NOT NULL, approver_id VARCHAR(120) DEFAULT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE approval_request');
    }
}
