<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260628205200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create chat sessions and agent runs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE chat_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_key VARCHAR(255) NOT NULL, platform VARCHAR(32) NOT NULL, team_id VARCHAR(255) NOT NULL, channel_id VARCHAR(255) NOT NULL, thread_id VARCHAR(255) NOT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, summary TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_chat_session_key ON chat_session (session_key)');
        $this->addSql('CREATE TABLE agent_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id INT NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, input_summary TEXT DEFAULT NULL, output_summary TEXT DEFAULT NULL, context_snapshot TEXT DEFAULT NULL, input_tokens INT DEFAULT NULL, output_tokens INT DEFAULT NULL, total_tokens INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_agent_run_session_id ON agent_run (session_id)');
        $this->addSql('ALTER TABLE agent_run ADD CONSTRAINT FK_agent_run_session_id FOREIGN KEY (session_id) REFERENCES chat_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE agent_run DROP CONSTRAINT FK_agent_run_session_id');
        $this->addSql('DROP TABLE agent_run');
        $this->addSql('DROP TABLE chat_session');
    }
}
