<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260628214400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Linear write audit records.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE linear_write_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operation VARCHAR(64) NOT NULL, source_message_id VARCHAR(160) NOT NULL, workflow_name VARCHAR(120) NOT NULL, requester_id VARCHAR(120) NOT NULL, target_issue_identifier VARCHAR(80) DEFAULT NULL, resulting_issue_identifiers JSON NOT NULL, status VARCHAR(32) NOT NULL, failure_summary TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE linear_write_audit');
    }
}
